<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
        <AssemblyAttribute>System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage</AssemblyAttribute>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\DurationMancer\DurationMancer.csproj" />
    </ItemGroup>

</Project>
